chore: several config changes

diff --git a/.config/rofi/rofi-power-menu b/.config/rofi/rofi-power-menu
--- a/.config/rofi/rofi-power-menu
+++ b/.config/rofi/rofi-power-menu
@@ -38,9 +38,9 @@ icons[shutdown]="\uf011"
 icons[cancel]="\uf05e"
 
 declare -A actions
-actions[lockscreen]="loginctl lock-session $XDG_SESSION_ID"
+actions[lockscreen]="loginctl lock-session ${XDG_SESSION_ID-}"
 #actions[switchuser]="???"
-actions[logout]="loginctl terminate-session $XDG_SESSION_ID"
+actions[logout]="loginctl terminate-session ${XDG_SESSION_ID-}"
 actions[suspend]="systemctl suspend"
 actions[hibernate]="systemctl hibernate"
 actions[reboot]="systemctl reboot"
@@ -52,6 +52,7 @@ confirmations=(reboot shutdown logout)
 # By default, no dry run
 dryrun=false
 showsymbols=true
+showtext=true
 
 function check_valid {
   option="$1"
@@ -65,7 +66,7 @@ function check_valid {
 }
 
 # Parse command-line options
-parsed=$(getopt --options=h --longoptions=help,dry-run,confirm:,choices:,choose:,symbols,no-symbols --name "$0" -- "$@")
+parsed=$(getopt --options=h --longoptions=help,dry-run,confirm:,choices:,choose:,symbols,no-symbols,text,no-text,symbols-font: --name "$0" -- "$@")
 if [ $? -ne 0 ]; then
   echo 'Terminating...' >&2
   exit 1
@@ -85,26 +86,31 @@ while true; do
     echo "  rofi -show menu -modi \"menu:rofi-power-menu --choices=shutdown/reboot\""
     echo
     echo "Available options:"
-    echo "  --dry-run          Don't perform the selected action but print it to stderr."
-    echo "  --choices CHOICES  Show only the selected choices in the given order. Use / "
-    echo "                     as the separator. Available choices are lockscreen, logout,"
-    echo "                     suspend, hibernate, reboot and shutdown. By default, all"
-    echo "                     available choices are shown."
-    echo "  --confirm CHOICES  Require confirmation for the gives choices only. Use / as"
-    echo "                     the separator. Available choices are lockscreen, logout,"
-    echo "                     suspend, hibernate, reboot and shutdown. By default, only"
-    echo "                     irreversible actions logout, reboot and shutdown require"
-    echo "                     confirmation."
-    echo "  --choose CHOICE    Preselect the given choice and only ask for a confirmation"
-    echo "                     (if confirmation is set to be requested). It is strongly"
-    echo "                     recommended to combine this option with --confirm=CHOICE"
-    echo "                     if the choice wouldn't require confirmation by default."
-    echo "                     Available choices are lockscreen, logout, suspend,"
-    echo "                     hibernate, reboot and shutdown."
-    echo "  --[no-]symbols     Show Unicode symbols or not. Requires a font with support"
-    echo "                     for the symbols. Use, for instance, fonts from the"
-    echo "                     Nerdfonts collection. By default, they are shown"
-    echo "  -h,--help          Show this help text."
+    echo "  --dry-run            Don't perform the selected action but print it to stderr."
+    echo "  --choices CHOICES    Show only the selected choices in the given order. Use /"
+    echo "                       as the separator. Available choices are lockscreen,"
+    echo "                       logout,suspend, hibernate, reboot and shutdown. By"
+    echo "                       default, all available choices are shown."
+    echo "  --confirm CHOICES    Require confirmation for the gives choices only. Use / as"
+    echo "                       the separator. Available choices are lockscreen, logout,"
+    echo "                       suspend, hibernate, reboot and shutdown. By default, only"
+    echo "                       irreversible actions logout, reboot and shutdown require"
+    echo "                       confirmation."
+    echo "  --choose CHOICE      Preselect the given choice and only ask for a"
+    echo "                       confirmation (if confirmation is set to be requested). It"
+    echo "                       is strongly recommended to combine this option with"
+    echo "                       --confirm=CHOICE if the choice wouldn't require"
+    echo "                       confirmation by default. Available choices are"
+    echo "                       lockscreen, logout, suspend, hibernate, reboot and"
+    echo "                       shutdown."
+    echo "  --[no-]symbols       Show Unicode symbols or not. Requires a font with support"
+    echo "                       for the symbols. Use, for instance, fonts from the"
+    echo "                       Nerdfonts collection. By default, they are shown"
+    echo "  --[no-]text          Show text description or not."
+    echo "  --symbols-font FONT  Use the given font for symbols. By default, the symbols"
+    echo "                       use the same font as the text. That font is configured"
+    echo "                       with rofi."
+    echo "  -h,--help            Show this help text."
     exit 0
     ;;
   "--dry-run")
@@ -135,6 +141,18 @@ while true; do
     showsymbols=false
     shift 1
     ;;
+  "--text")
+    showtext=true
+    shift 1
+    ;;
+  "--no-text")
+    showtext=false
+    shift 1
+    ;;
+  "--symbols-font")
+    symbols_font="$2"
+    shift 2
+    ;;
   "--")
     shift
     break
@@ -146,22 +164,30 @@ while true; do
   esac
 done
 
+if [ "$showsymbols" = "false" -a "$showtext" = "false" ]; then
+  echo "Invalid options: cannot have --no-symbols and --no-text enabled at the same time." >&2
+  exit 1
+fi
+
 # Define the messages after parsing the CLI options so that it is possible to
 # configure them in the future.
 
 function write_message {
-  icon="<span font_size=\"medium\">$1</span>"
+  if [ -z ${symbols_font+x} ]; then
+    icon="<span font_size=\"medium\">$1</span>"
+  else
+    icon="<span font=\"${symbols_font}\" font_size=\"medium\">$1</span>"
+  fi
   text="<span font_size=\"medium\">$2</span>"
   if [ "$showsymbols" = "true" ]; then
-    echo -n "\u200e$icon \u2068$text\u2069"
+    if [ "$showtext" = "true" ]; then
+      echo -n "\u200e$icon \u2068$text\u2069"
+    else
+      echo -n "\u200e$icon"
+    fi
   else
     echo -n "$text"
   fi
-}
-
-function write_icon {
-  icon="<span font_size=\"medium\">$1</span>"
-  echo -n "$icon"
 }
 
 function print_selection {
@@ -177,9 +203,9 @@ for entry in "${all[@]}"; do
   messages[$entry]=$(write_message "${icons[$entry]}" "${texts[$entry]^}")
 done
 for entry in "${all[@]}"; do
-  confirmationMessages[$entry]=$(write_message "${icons[$entry]}" "Yes")
+  confirmationMessages[$entry]=$(write_message "${icons[$entry]}" "Yes, ${texts[$entry]}")
 done
-confirmationMessages[cancel]=$(write_message "${icons[cancel]}" "No")
+confirmationMessages[cancel]=$(write_message "${icons[cancel]}" "No, cancel")
 
 if [ $# -gt 0 ]; then
   # If arguments given, use those as the selection
@@ -197,7 +223,7 @@ echo -e "\0no-custom\x1ftrue"
 echo -e "\0markup-rows\x1ftrue"
 
 if [ -z "${selection+x}" ]; then
-  echo -e "\0prompt\x1fPower menu"
+  echo -e "\0prompt\x1fPower menu "
   for entry in "${show[@]}"; do
     echo -e "${messages[$entry]}\0icon\x1f${icons[$entry]}"
   done
